name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: MontyD/package-json-updated-action@0.1.0
      id: version-updated
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
      if: steps.version-updated.outputs.has-updated
    - uses: actions/setup-node@v1
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: '12.x'
    - run: npm install
      if: steps.version-updated.outputs.has-updated
    - run: npm run build
      if: steps.version-updated.outputs.has-updated
    - name: Create GH release
      if: steps.version-updated.outputs.has-updated
      uses: softprops/action-gh-release@v1
      with:
        files: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
