name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  pubish-release-if-needed:
    runs-on: ubuntu-latest
    steps:
    - uses: MontyD/package-json-updated-action@0.2.0
      id: version-updated
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v1
      if: steps.version-updated.outputs.has-updated
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      if: steps.version-updated.outputs.has-updated
      with:
        node-version: '12.x'
    - run: npm install
      if: steps.version-updated.outputs.has-updated
    - run: npm run build && npm run tar-dist
      if: steps.version-updated.outputs.has-updated
    - name: Create Release
      if: steps.version-updated.outputs.has-updated
      id: create-release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version-updated.outputs.current-package-version }}
        release_name: Release ${{ steps.version-updated.outputs.current-package-version }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      if: steps.version-updated.outputs.has-updated
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./dist.tar.gz
        asset_name: dist.tar.gz
        asset_content_type: application/gzip
